version: "3.9"

services:
  default:
    build:
      context: ./postgresql
      args:
        - POSTGRES_PASSWORD
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    build:
      context: ./pgadmin
      args:
        - PGADMIN_DEFAULT_EMAIL
        - PGADMIN_DEFAULT_PASSWORD
    ports:
      - 80:80
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
  pgadmin:
